
import React, { useState, useContext, useMemo, useRef } from 'react';
import { ProjectContext } from '../../contexts/ProjectContext';
import Button from '../Button';
import { ChartBarIcon, Loader, SparklesIcon, TrashIcon, ArrowsRightLeftIcon, SwatchIcon, PhotoIcon, DocumentTextIcon, MagicWandIcon } from '../Icons';
import * as geminiService from '../../services/geminiService';
import { setItem, getItem } from '../../utils/localStorage';
import { ARCHIVE_STORAGE_KEY, INFOGRAPHIC_LAYOUTS, INFOGRAPHIC_STYLES, GRAPHIC_DESIGN_SIZES } from '../../constants';
import CustomGroupedSelect from '../CustomGroupedSelect';
import { AdvancedColorPicker } from '../AdvancedColorPicker';
import CopyButton from '../CopyButton';
import ExportMenu from '../ExportMenu';

interface InfoPoint {
    id: string;
    title: string;
    description: string;
    icon: string;
}

const InfographicDesignerView: React.FC = () => {
    const { appLanguage, topic } = useContext(ProjectContext);
    const isAr = appLanguage === 'ar';

    // State
    const [mainTopic, setMainTopic] = useState(topic);
    const [points, setPoints] = useState<InfoPoint[]>([
        { id: '1', title: '', description: '', icon: '💡' },
        { id: '2', title: '', description: '', icon: '🚀' },
        { id: '3', title: '', description: '', icon: '📈' }
    ]);
    
    const [layout, setLayout] = useState('Timeline');
    const [style, setStyle] = useState('Flat Vector');
    const [size, setSize] = useState('1:1');
    const [colors, setColors] = useState<string[]>(['#bf8339', '#0a1e3c', '#ffffff']);
    const [renderTextMode, setRenderTextMode] = useState<'ai_text' | 'layout_only'>('ai_text');

    const [isLoadingData, setIsLoadingData] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const [resultImage, setResultImage] = useState<string | null>(null);
    
    const fileRef = useRef<HTMLInputElement>(null);

    // Helpers
    const handleAddPoint = () => {
        setPoints([...points, { id: Date.now().toString(), title: '', description: '', icon: '✨' }]);
    };

    const handleRemovePoint = (id: string) => {
        if (points.length > 1) {
            setPoints(points.filter(p => p.id !== id));
        }
    };

    const handleUpdatePoint = (id: string, field: keyof InfoPoint, value: string) => {
        setPoints(points.map(p => p.id === id ? { ...p, [field]: value } : p));
    };

    // Auto-Generate Data (Text Topic)
    const handleAutoGenerateData = async () => {
        if (!mainTopic) return alert(isAr ? 'يرجى كتابة موضوع أولاً' : 'Please enter a topic first');
        setIsLoadingData(true);
        try {
            const data = await geminiService.generateInfographicContent(mainTopic, points.length || 4, isAr ? 'Arabic' : 'English');
            // Map to current structure
            const newPoints = data.map((d: any, i: number) => ({
                id: Date.now().toString() + i,
                title: d.title,
                description: d.description,
                icon: d.icon || '🔹'
            }));
            setPoints(newPoints);
        } catch (e) {
            console.error(e);
            alert(isAr ? 'فشل توليد البيانات' : 'Failed to generate data');
        } finally {
            setIsLoadingData(false);
        }
    };

    // Magic Image Import
    const handleMagicImageImport = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        
        setIsLoadingData(true);
        const reader = new FileReader();
        reader.onloadend = async () => {
            try {
                const base64 = (reader.result as string).split(',')[1];
                // 1. Extract Text
                const extractedText = await geminiService.extractTextFromImage(base64, file.type);
                if (!extractedText || extractedText.length < 10) throw new Error("No extracted text");
                
                // 2. Generate Points from extracted text
                const data = await geminiService.generateInfographicPointsFromText(extractedText, points.length || 4, isAr ? 'Arabic' : 'English');
                
                const newPoints = data.map((d: any, i: number) => ({
                    id: Date.now().toString() + i,
                    title: d.title,
                    description: d.description,
                    icon: d.icon || '🔹'
                }));
                setPoints(newPoints);
                if (fileRef.current) fileRef.current.value = '';
                
                if ((window as any).toast) {
                    (window as any).toast(isAr ? 'تم استخلاص البيانات بنجاح!' : 'Data extracted successfully!', 'success');
                }

            } catch (e) {
                console.error(e);
                alert(isAr ? 'فشل استخلاص البيانات من الصورة' : 'Failed to extract data from image');
            } finally {
                setIsLoadingData(false);
            }
        };
        reader.readAsDataURL(file);
    };

    // Generate Image
    const handleGenerateImage = async () => {
        // Validation
        if (points.some(p => !p.title)) return alert(isAr ? 'يرجى تعبئة عناوين النقاط' : 'Please fill point titles');
        
        // Key Check for Pro Model
        if ((window as any).aistudio) {
            try {
               const hasKey = await (window as any).aistudio.hasSelectedApiKey();
               if (!hasKey) {
                   await (window as any).aistudio.openSelectKey();
               }
            } catch (e) { console.warn("Key check failed", e); }
        }

        setIsGenerating(true);
        setResultImage(null);

        try {
            const imageBase64 = await geminiService.generateInfographic(
                points,
                style,
                layout,
                colors,
                size,
                isAr ? 'ar' : 'en',
                renderTextMode === 'ai_text'
            );
            
            setResultImage(imageBase64);
            
            // Save to Archive
            const archive = getItem(ARCHIVE_STORAGE_KEY, []);
            archive.unshift({ 
                id: Date.now().toString(), 
                type: 'Infographic', 
                content: imageBase64, 
                timestamp: new Date().toISOString() 
            });
            setItem(ARCHIVE_STORAGE_KEY, archive);

        } catch (e: any) {
            console.error(e);
            alert(e.message || (isAr ? 'فشل إنشاء الانفوجرافيك' : 'Failed to generate infographic'));
            if (e.message?.includes("Requested entity was not found") && (window as any).aistudio) {
                await (window as any).aistudio.openSelectKey();
            }
        } finally {
            setIsGenerating(false);
        }
    };

    // Dropdown Groups
    const layoutGroups = useMemo(() => [{
        label: isAr ? 'أنماط التخطيط' : 'Layout Styles',
        options: INFOGRAPHIC_LAYOUTS.map(l => ({ 
            label: isAr ? `${l.icon} ${l.label.ar}` : `${l.icon} ${l.label.en}`, 
            value: l.value 
        }))
    }], [isAr]);

    const styleGroups = useMemo(() => [{
        label: isAr ? 'الأسلوب الفني' : 'Art Style',
        options: INFOGRAPHIC_STYLES.map(s => ({
            label: isAr ? s.label.ar : s.label.en,
            value: s.value
        }))
    }], [isAr]);

    // Use comprehensive sizes from Graphic Designer
    const sizeGroups = useMemo(() => GRAPHIC_DESIGN_SIZES.map(g => ({
        label: isAr ? g.label.ar : g.label.en,
        options: g.options.map(o => ({
            label: isAr ? o.label.ar : o.label.en,
            value: o.value
        }))
    })), [isAr]);

    return (
        <div className="space-y-6 animate-fade-in pb-20">
            {/* Header */}
            <div className="flex justify-between items-end border-b border-white/10 pb-4">
                <div>
                    <h2 className="text-3xl font-bold text-[#bf8339] flex items-center gap-2">
                        <ChartBarIcon className="w-8 h-8" /> 
                        {isAr ? 'صانع الانفوجرافيك الذكي' : 'Smart Infographic Designer'}
                    </h2>
                    <p className="text-white/60 mt-1">
                        {isAr 
                            ? 'حول البيانات المعقدة أو الصور إلى تصاميم بصرية مذهلة ومريحة للعين.' 
                            : 'Turn complex data or images into stunning, eye-pleasing visual designs.'}
                    </p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                
                {/* LEFT PANEL: Inputs & Data */}
                <div className="lg:col-span-5 space-y-6">
                    {/* 1. Content & Data */}
                    <div className="bg-[#0a1e3c]/60 backdrop-blur border border-white/10 rounded-xl p-5 shadow-lg">
                        <h3 className="text-[#bf8339] font-bold mb-4 text-sm uppercase tracking-wider border-b border-white/10 pb-2">
                            {isAr ? '1. المحتوى والبيانات' : '1. Content & Data'}
                        </h3>
                        
                        {/* MAGIC IMPORT SECTION */}
                        <div 
                            onClick={() => fileRef.current?.click()}
                            className="border-2 border-dashed border-[#bf8339]/30 bg-[#bf8339]/5 hover:bg-[#bf8339]/10 hover:border-[#bf8339] rounded-xl p-4 mb-4 flex flex-col items-center justify-center cursor-pointer transition group text-center"
                        >
                            <MagicWandIcon className="w-8 h-8 text-[#bf8339] mb-2 group-hover:scale-110 transition-transform" />
                            <p className="text-sm font-bold text-[#bf8339]">{isAr ? 'استيراد ذكي من صورة' : 'Smart Import from Image'}</p>
                            <p className="text-[10px] text-white/50 mt-1 max-w-[200px]">
                                {isAr ? 'ارفع صورة (مستند، شريحة، ملاحظات) لاستخلاص البيانات تلقائياً' : 'Upload image (doc, slide, notes) to extract data automatically'}
                            </p>
                            <input type="file" ref={fileRef} onChange={handleMagicImageImport} className="hidden" accept="image/*" />
                        </div>

                        <div className="flex gap-2 mb-4">
                            <input 
                                type="text" 
                                className="flex-1 bg-black/20 border border-white/10 rounded-lg px-3 py-2 text-white focus:border-[#bf8339] text-sm"
                                placeholder={isAr ? "أو اكتب الموضوع هنا..." : "Or type topic here..."}
                                value={mainTopic}
                                onChange={e => setMainTopic(e.target.value)}
                            />
                            <Button 
                                variant="secondary" 
                                onClick={handleAutoGenerateData} 
                                isLoading={isLoadingData}
                                className="!py-2 !px-3 !text-xs whitespace-nowrap"
                            >
                                <SparklesIcon className="w-4 h-4 mr-1" />
                                {isAr ? 'توليد' : 'Generate'}
                            </Button>
                        </div>

                        {/* Manual Points List */}
                        <div className="space-y-3 max-h-[400px] overflow-y-auto custom-scrollbar pr-1">
                            {isLoadingData && (
                                <div className="text-center py-4">
                                    <Loader />
                                    <p className="text-xs text-white/50 mt-2">{isAr ? 'جاري تحليل البيانات...' : 'Analyzing data...'}</p>
                                </div>
                            )}
                            
                            {!isLoadingData && points.map((point, index) => (
                                <div key={point.id} className="bg-white/5 p-3 rounded-lg border border-white/5 hover:border-[#bf8339]/30 transition group">
                                    <div className="flex justify-between items-center mb-2">
                                        <div className="flex items-center gap-2">
                                            <span className="bg-[#bf8339] text-[#0a1e3c] w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold">{index + 1}</span>
                                            <input 
                                                type="text" 
                                                className="bg-transparent border-b border-white/10 text-white font-bold text-sm w-32 focus:border-[#bf8339] outline-none"
                                                placeholder={isAr ? "العنوان" : "Title"}
                                                value={point.title}
                                                onChange={e => handleUpdatePoint(point.id, 'title', e.target.value)}
                                            />
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <input 
                                                type="text" 
                                                className="bg-black/30 w-8 h-8 rounded text-center text-lg focus:ring-1 focus:ring-[#bf8339] outline-none"
                                                value={point.icon}
                                                onChange={e => handleUpdatePoint(point.id, 'icon', e.target.value)}
                                                maxLength={2}
                                            />
                                            <button onClick={() => handleRemovePoint(point.id)} className="text-white/20 hover:text-red-400">
                                                <TrashIcon className="w-4 h-4" />
                                            </button>
                                        </div>
                                    </div>
                                    <textarea 
                                        className="w-full bg-black/10 text-white/70 text-xs p-2 rounded resize-none focus:bg-black/20 outline-none"
                                        rows={2}
                                        placeholder={isAr ? "الوصف المختصر..." : "Short description..."}
                                        value={point.description}
                                        onChange={e => handleUpdatePoint(point.id, 'description', e.target.value)}
                                    />
                                </div>
                            ))}
                        </div>
                        <button onClick={handleAddPoint} className="w-full mt-3 py-2 border border-dashed border-white/20 rounded-lg text-white/50 hover:text-white hover:border-white transition text-xs font-bold">
                            + {isAr ? 'إضافة نقطة يدوياً' : 'Add Point Manually'}
                        </button>
                    </div>

                    {/* 2. Visual Settings */}
                    <div className="bg-[#0a1e3c]/60 backdrop-blur border border-white/10 rounded-xl p-5 shadow-lg">
                        <h3 className="text-[#bf8339] font-bold mb-4 text-sm uppercase tracking-wider border-b border-white/10 pb-2">
                            {isAr ? '2. الإخراج الفني' : '2. Visual Style'}
                        </h3>
                        
                        <div className="space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <CustomGroupedSelect label={isAr ? "التخطيط (Layout)" : "Layout"} value={layout} onChange={setLayout} groups={layoutGroups} placeholder="Select Layout" />
                                <CustomGroupedSelect label={isAr ? "الستايل (Style)" : "Style"} value={style} onChange={setStyle} groups={styleGroups} placeholder="Select Style" />
                            </div>
                            <CustomGroupedSelect label={isAr ? "الأبعاد (All Sizes)" : "Dimensions"} value={size} onChange={setSize} groups={sizeGroups} placeholder="Select Size" />
                            
                            <AdvancedColorPicker 
                                label={isAr ? "لوحة الألوان" : "Color Palette"} 
                                onColorChange={setColors} 
                                defaultColors={colors} 
                                isAr={isAr}
                            />
                        </div>
                    </div>
                </div>

                {/* RIGHT PANEL: Preview & Generation */}
                <div className="lg:col-span-7 space-y-6">
                    {/* Text Rendering Mode Toggle */}
                    <div className="bg-white/5 border border-white/10 rounded-xl p-4 flex flex-col md:flex-row justify-between items-center gap-4">
                        <div className="flex-1">
                            <h4 className="text-white font-bold text-sm mb-1">{isAr ? 'وضع النصوص' : 'Text Mode'}</h4>
                            <p className="text-[10px] text-white/50">
                                {isAr 
                                    ? 'اختر "كتابة AI" لمحاولة كتابة النصوص داخل الصورة، أو "تخطيط فارغ" لإضافة نصوصك لاحقاً بمحرر خارجي.' 
                                    : 'Choose "AI Text" to render text in image, or "Layout Only" for blank placeholders.'}
                            </p>
                        </div>
                        <div className="flex bg-black/30 p-1 rounded-lg">
                            <button 
                                onClick={() => setRenderTextMode('ai_text')}
                                className={`px-4 py-2 rounded-md text-xs font-bold transition ${renderTextMode === 'ai_text' ? 'bg-[#bf8339] text-[#0a1e3c]' : 'text-white/60 hover:text-white'}`}
                            >
                                {isAr ? 'كتابة AI (تجريبي)' : 'AI Text (Beta)'}
                            </button>
                            <button 
                                onClick={() => setRenderTextMode('layout_only')}
                                className={`px-4 py-2 rounded-md text-xs font-bold transition ${renderTextMode === 'layout_only' ? 'bg-[#bf8339] text-[#0a1e3c]' : 'text-white/60 hover:text-white'}`}
                            >
                                {isAr ? 'تخطيط فارغ (Layout)' : 'Layout Only'}
                            </button>
                        </div>
                    </div>

                    <Button 
                        onClick={handleGenerateImage} 
                        isLoading={isGenerating} 
                        className="w-full py-4 text-lg font-bold shadow-xl shadow-[#bf8339]/20"
                    >
                        {isGenerating 
                            ? (isAr ? 'جاري الرسم الهندسي (قد يستغرق دقيقة)...' : 'Designing (takes a minute)...') 
                            : (isAr ? 'إنشاء الانفوجرافيك' : 'Generate Infographic')
                        }
                    </Button>

                    {/* Output Area */}
                    <div className="bg-black/40 border border-[#bf8339]/30 rounded-xl min-h-[500px] flex items-center justify-center relative overflow-hidden group">
                        {resultImage ? (
                            <>
                                <img src={resultImage} alt="Generated Infographic" className="max-w-full max-h-[600px] shadow-2xl rounded-lg" />
                                <div className="absolute bottom-4 right-4 flex gap-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                    <ExportMenu content={resultImage} type="image" filename={`infographic-${Date.now()}`} label={isAr ? "تحميل" : "Download"} />
                                </div>
                            </>
                        ) : (
                            <div className="text-center text-white/20 p-8">
                                <ChartBarIcon className="w-24 h-24 mx-auto mb-4 opacity-50" />
                                <p className="text-lg">{isAr ? 'مساحة العرض' : 'Preview Area'}</p>
                                <p className="text-sm mt-2 max-w-xs mx-auto">{isAr ? 'ستظهر هنا النتيجة النهائية بتفاصيل فائقة الجودة.' : 'High quality result will appear here.'}</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default InfographicDesignerView;
